
- name: Install PostgreSQL
  apt:
    update_cache: yes
    name: postgresql
    state: present
  become: yes

- name: Ensure PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: Update pg_hba.conf to allow md5 authentication
  lineinfile:
    path: /etc/postgresql/15/main/pg_hba.conf
    regexp: '^local\\s+all\\s+all\\s+peer'
    line: 'local   all             all                                     md5'
    state: present
  become: yes
  notify: Restart PostgreSQL

- name: Create databases
  community.postgresql.postgresql_db:
    name: "{{ item }}"
    owner: postgres
    state: present
    login_user: postgres
    login_password: "{{ postgresql_password }}"
  loop: "{{ bdd_databases }}"
  become: yes

